### ISSUE TITLE
Issue about fee-charging feature

### ISSUE THREAD

**Issue by Liamgettingbetter** [SmartMeshFoundation/Photon#23]
Does anybody know that our SmartRaiden service add feature like charging fee? According to Raiden 101, when users try to use feature like MediateTransfer, it seems like they need to pay fees to those mediate router.

How about our SmartRaiden? Do we also need to take a charge while furthering transfers ?

**Comment by nkbai** [comment]
photon supports mediated node  charging fee right now.
