### ISSUE TITLE
Issue about compatibility of SmartRaiden Message

### ISSUE THREAD

**Issue by Liamgettingbetter** [SmartMeshFoundation/Photon#34]
## Issue Definition
Message Version of SmartRaiden have to be forward and backward compatible.

## Specification

- We are going to design the message as a forward and backward compatible, so that any node can send out and receive messages of older or newer version. 
- In order to achieve this feature, what we have to do are 
    - We can't reduce fields in the data structure of message, which means that updated version message just has additional fields but not less. 
    - Even some fields are no longer used in future version, we still need to assign proper value for them when newer message structure is adopted. 
- Support a new handshake mechanism, comprising of messages with features like when talking to other node, he can decide to send messages compatible to that node.

**Comment by nkbai** [comment]
The version information is already included in the message. If it is a compatible message, it can be processed.
