### ISSUE TITLE
Issue about risks for forking attack.

### ISSUE THREAD

**Issue by Liamgettingbetter** [SmartMeshFoundation/Photon#36]
Due to the potential risk of hard-fork, there is a strong need for us to better design our codebase, like `Deposit`, we may consider some amount of confirmation blocks, as 12 blocks. After that amount, the transfer can take effect. The same condition should be applied to `Openchannel` and so on. 

On the other hand, like `CloseChannel` or `Settle`, these state transitions should take effect as soon as they have been invoked.

Potential risks of crash exist among all these state transitions, we should also consider crash recovery of them.

**Comment by nkbai** [comment]
have fixed this problem
